export const cities: string[] = [
    "Los Angeles",
    "San Francisco",
    "San Diego",
    "Sacramento",
    "San Jose",
    "Fresno",
    "Long Beach",
    "Oakland",
    "Bakersfield",
    "Anaheim",
    "Santa Barbara",
    "Riverside",
    "Chula Vista",
    "Irvine",
    "Santa Monica",
    "Pasadena",
    "Berkeley",
    "Palm Springs",
    "Modesto",
    "Stockton",
    "Chico",
    "Santa Rosa",
    "Temecula",
    "Redwood City",
    "Mountain View",
    "Sunnyvale",
    "Torrance",
    "Carlsbad",
    "Livermore",
    "San Luis Obispo",
    "Camarillo",
    "Clovis",
    "Manteca",
    "Lodi",
    "El Cajon",
    "Culver City",
    "La Mesa",
    "Simi Valley",
    "Folsom",
    "Rancho Cucamonga",
    "Chino Hills",
    "Lakewood",
    "Tustin",
    "Rancho Cordova",
    "Citrus Heights",
    "Chino",
    "La Habra",
    "Lynwood",
];

export const states: string[] = ["California"];

export const countries: string[] = ["United States"];

export const propertyConditions: string[] = [
    "Excellent",
    "Good",
    "Average",
    "Fair",
    "Poor",
];
